### ISSUE TITLE
Make the heading and sub-heading centrally aligned.

### ISSUE THREAD

**Issue by ishaanbedi** [ishaanbedi/covtrack#1]
The text CovTrack & Covid Tracker should be centrally aligned on the page.
We are using PicoCSS to style the page, check out more at https://picocss.com/.

**Comment by joanjeremiah** [comment]
Kindly assign this task to me

**Comment by ishaanbedi** [comment]
> Kindly assign this task to me

Go ahead! 
Let me know if you need any help

**Comment by joanjeremiah** [comment]
I have made a pull request kindly look into it and let me know if there is a need to make changes

**Comment by ishaanbedi** [comment]
> I have made a pull request kindly look into it and let me know if there is a need to make changes

Well done! Merged the PR.
