### ISSUE TITLE
Add a toggle button to switch themes [Dark/Light]

### ISSUE THREAD

**Issue by ishaanbedi** [ishaanbedi/covtrack#16]
See https://picocss.com/ for more on changing themes and styles.

**Comment by itzwow** [comment]
I would like to work on this issue

**Comment by ELIJAHJOHNNY** [comment]
Hi @ishaanbedi can you please assign this to me?

**Comment by ishaanbedi** [comment]
Go ahead @ELIJAHJOHNNY

**Comment by itzwow** [comment]
If this issue is still pending I would like to work on it

**Comment by divyanshu27088** [comment]
i would like to work on this.

**Comment by ELIJAHJOHNNY** [comment]
@ishaanbedi Hello!! I am so sorry for the delay, I lost access to my devices that was why I could not push to the repository since. I already finished the work since. So can I still push now, thanks as I await your response

**Comment by ELIJAHJOHNNY** [comment]
@ishaanbedi  Pushed already though, just waiting for your response so I can send a pull request for it to be merged. Thanks

**Comment by ishaanbedi** [comment]
> @ishaanbedi Pushed already though, just waiting for your response so I can send a pull request for it to be merged. Thanks

Hi @ELIJAHJOHNNY , so sorry but the feature has already been worked upon by @divyanshu27088 !
If you want, you may work on #17 as it's still pending. 
Again, so sorry!
