### ISSUE TITLE
Setup an action to show name of contributors at the bottom of the page.

### ISSUE THREAD

**Issue by ishaanbedi** [ishaanbedi/covtrack#17]

**Comment by sandilya27** [comment]
I can work on this please specify you want it in the last or in the footer section which is sticky throughout?

**Comment by ishaanbedi** [comment]
> I can work on this please specify you want it in the last or in the footer section which is sticky throughout?

In the last, though I'm open to suggestions wherever you like!
Anyways, assigning you!
