### ISSUE TITLE
Change the text “Data as of 29/9/2022” format to “Data last fetched on 29/9/2022.”

### ISSUE THREAD

**Issue by ishaanbedi** [ishaanbedi/covtrack#3]

**Comment by Rounak-28** [comment]
@ishaanbedi  I will do this.

**Comment by ishaanbedi** [comment]
Go ahead, all the best!

**Comment by ishaanbedi** [comment]
Hi @Rounak-28 , the issue is already resolved. You may leave this one and start working on https://github.com/ishaanbedi/covtrack/issues/5 if you wish to.
