### ISSUE TITLE
Add a tooltip to Global Data as “Data fetched from covid19api.com”.

### ISSUE THREAD

**Issue by ishaanbedi** [ishaanbedi/covtrack#4]
Refer to https://picocss.com/ for more information on how to add a tooltip.

**Comment by prateek-1606** [comment]
Hi @ishaanbedi can you assign this issue to me.

**Comment by joanjeremiah** [comment]
Kindly assign this task to me @ishaanbedi

**Comment by ishaanbedi** [comment]
Go ahead @prateek-1606 , all the best!

**Comment by joanjeremiah** [comment]
Is the issue closed ? If not, Can I give it a try?

**Comment by ishaanbedi** [comment]
@joanjeremiah Go ahead!

**Comment by joanjeremiah** [comment]
@ishaanbedi It seems that @prateek-1606 has already added a tooltip. Do you still want me to work on this?

**Comment by ishaanbedi** [comment]
> @ishaanbedi It seems that @prateek-1606 has already added a tooltip. Do you still want me to work on this?

Yeah I forgot to close the issue!
Don't worry, you may work on a similar issue by adding a tooltip for the Indian data!
All the best!

**Comment by joanjeremiah** [comment]
@ishaanbedi Thanks. I will work on that issue.

**Comment by joanjeremiah** [comment]
@ishaanbedi I added the tooltip for Indian data and made a pull request. Kindly look into it.
